# Docker profile — overrides local settings
spring.application.name=school-management-system
server.port=8080

# MongoDB points to the Docker service name "mongo"
spring.data.mongodb.uri=mongodb://mongo:27017/school_management

logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO
logging.level.org.springframework.web=INFO
logging.level.com.niit.sms=INFO

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null

spring.web.resources.static-locations=classpath:/static/